import type { Entry, Provider } from "./types";
import { defaultCollections, schemaPresets } from "./workspace-defaults";
export { defaultCollections, schemaPresets } from "./workspace-defaults";

const githubSchema = schemaPresets[0]!;
const tangledSchema = schemaPresets[1]!;

export const defaultProviders: Provider[] = [
	{
		id: "github",
		name: "GitHub",
		kind: "github",
		handle: "@alex",
		description: "Starred repositories and topic metadata.",
		accent: "#8b7cff",
		schema: githubSchema,
		connected: true,
		connectedAt: "2026-08-21T08:10:00.000Z",
		lastSyncedAt: "2026-09-08T14:31:00.000Z",
	},
	{
		id: "tangled",
		name: "Tangled",
		kind: "tangled",
		handle: "did:plc:alex",
		description: "Stars and follows across the AT Protocol graph.",
		accent: "#54c7a8",
		schema: tangledSchema,
		connected: true,
		connectedAt: "2026-08-24T17:42:00.000Z",
		lastSyncedAt: "2026-09-08T14:29:00.000Z",
	},
];

const ago = (days: number, hours = 0) => {
	const date = new Date("2026-09-08T14:35:00.000Z");
	date.setDate(date.getDate() - days);
	date.setHours(date.getHours() - hours);
	return date.toISOString();
};

export const defaultEntries: Entry[] = [
	{
		id: "github-vercel-ai",
		providerId: "github",
		schemaId: githubSchema.id,
		kind: "repository",
		title: "vercel / ai",
		summary: "Build AI-powered products with React, Svelte, Vue, and Solid.",
		url: "https://github.com/vercel/ai",
		author: "Vercel",
		authorHandle: "vercel",
		tags: ["ai", "typescript", "react"],
		starredAt: ago(1, 3),
		updatedAt: ago(0, 7),
		syncedAt: ago(0, 1),
		isRead: false,
		isPinned: true,
		language: "TypeScript",
		languageColor: "#3178c6",
		stars: 15200,
		forks: 2400,
	},
	{
		id: "tangled-fission",
		providerId: "tangled",
		schemaId: tangledSchema.id,
		kind: "repository",
		title: "fission / fission",
		summary: "A small, sharp web of composable tools for the open social web.",
		url: "https://tangled.org/fission/fission",
		author: "Fission",
		authorHandle: "@fission.codes",
		tags: ["atproto", "decentralized", "tools"],
		starredAt: ago(2, 6),
		updatedAt: ago(1, 8),
		syncedAt: ago(0, 2),
		isRead: false,
		isPinned: false,
		language: "Rust",
		languageColor: "#dea584",
		stars: 418,
		forks: 34,
	},
	{
		id: "github-astro",
		providerId: "github",
		schemaId: githubSchema.id,
		kind: "repository",
		title: "withastro / astro",
		summary: "The web framework for content-driven websites.",
		url: "https://github.com/withastro/astro",
		author: "Astro",
		authorHandle: "withastro",
		tags: ["frontend", "web", "performance"],
		starredAt: ago(4, 2),
		updatedAt: ago(1, 3),
		syncedAt: ago(0, 1),
		isRead: true,
		isPinned: false,
		language: "TypeScript",
		languageColor: "#3178c6",
		stars: 49800,
		forks: 4300,
	},
	{
		id: "tangled-pds",
		providerId: "tangled",
		schemaId: tangledSchema.id,
		kind: "repository",
		title: "atmosphere / pds-kit",
		summary: "Practical building blocks for portable, self-hosted data services.",
		url: "https://tangled.org/atmosphere/pds-kit",
		author: "Atmosphere",
		authorHandle: "@atmo.dev",
		tags: ["atproto", "self-hosting", "cloudflare"],
		starredAt: ago(5, 4),
		updatedAt: ago(3, 2),
		syncedAt: ago(0, 2),
		isRead: true,
		isPinned: false,
		language: "TypeScript",
		languageColor: "#3178c6",
		stars: 97,
		forks: 11,
	},
	{
		id: "github-effect",
		providerId: "github",
		schemaId: githubSchema.id,
		kind: "repository",
		title: "Effect-TS / effect",
		summary: "A powerful TypeScript library designed to help people easily create programs that are complex, synchronous, and asynchronous.",
		url: "https://github.com/Effect-TS/effect",
		author: "Effect",
		authorHandle: "Effect-TS",
		tags: ["typescript", "functional", "architecture"],
		starredAt: ago(7, 1),
		updatedAt: ago(2, 5),
		syncedAt: ago(0, 1),
		isRead: false,
		isPinned: false,
		language: "TypeScript",
		languageColor: "#3178c6",
		stars: 11800,
		forks: 620,
	},
	{
		id: "github-turso",
		providerId: "github",
		schemaId: githubSchema.id,
		kind: "repository",
		title: "tursodatabase / libsql",
		summary: "SQLite-compatible database with extensions for the modern edge.",
		url: "https://github.com/tursodatabase/libsql",
		author: "Turso",
		authorHandle: "tursodatabase",
		tags: ["database", "edge", "rust"],
		starredAt: ago(10, 5),
		updatedAt: ago(4, 1),
		syncedAt: ago(0, 1),
		isRead: true,
		isPinned: false,
		language: "Rust",
		languageColor: "#dea584",
		stars: 10400,
		forks: 490,
	},
	{
		id: "tangled-solar",
		providerId: "tangled",
		schemaId: tangledSchema.id,
		kind: "repository",
		title: "solarpunk / garden",
		summary: "A calm, local-first reference implementation for personal knowledge graphs.",
		url: "https://tangled.org/solarpunk/garden",
		author: "Solarpunk",
		authorHandle: "@garden.social",
		tags: ["local-first", "knowledge", "design"],
		starredAt: ago(13, 2),
		updatedAt: ago(5, 8),
		syncedAt: ago(0, 2),
		isRead: true,
		isPinned: false,
		language: "Go",
		languageColor: "#00add8",
		stars: 146,
		forks: 9,
	},
	{
		id: "github-shadcn-ui",
		providerId: "github",
		schemaId: githubSchema.id,
		kind: "repository",
		title: "shadcn-ui / ui",
		summary: "Beautifully designed components that you can copy and paste into your apps.",
		url: "https://github.com/shadcn-ui/ui",
		author: "shadcn",
		authorHandle: "shadcn",
		tags: ["design-system", "react", "components"],
		starredAt: ago(18, 4),
		updatedAt: ago(6, 4),
		syncedAt: ago(0, 1),
		isRead: false,
		isPinned: false,
		language: "TypeScript",
		languageColor: "#3178c6",
		stars: 92000,
		forks: 6800,
	},
];
