import type { Collection, Entry, Provider, ProviderSchema } from "./types";

export const schemaPresets: ProviderSchema[] = [
	{
		id: "github-repository",
		name: "Starred repositories",
		description: "Repositories, topics, languages, and the date you starred them.",
		icon: "github",
		defaultKind: "repository",
		fields: [
			{ id: "title", label: "Repository", type: "text", searchable: true },
			{ id: "summary", label: "Description", type: "text", searchable: true },
			{ id: "language", label: "Language", type: "text", searchable: true },
			{ id: "tags", label: "Topics", type: "tags", searchable: true },
			{ id: "stars", label: "Stars", type: "number" },
			{ id: "starredAt", label: "Starred at", type: "date" },
		],
	},
	{
		id: "tangled-repository",
		name: "Tangled stars",
		description: "AT Protocol repositories and conversations from Tangled.",
		icon: "branch",
		defaultKind: "repository",
		fields: [
			{ id: "title", label: "Repository", type: "text", searchable: true },
			{ id: "summary", label: "Description", type: "text", searchable: true },
			{ id: "authorHandle", label: "Author", type: "text", searchable: true },
			{ id: "tags", label: "Topics", type: "tags", searchable: true },
			{ id: "starredAt", label: "Starred at", type: "date" },
		],
	},
	{
		id: "web-bookmark",
		name: "Web bookmarks",
		description: "A general-purpose URL schema for any future bookmark provider.",
		icon: "bookmark",
		defaultKind: "bookmark",
		fields: [
			{ id: "title", label: "Title", type: "text", searchable: true },
			{ id: "summary", label: "Notes", type: "text", searchable: true },
			{ id: "url", label: "URL", type: "url", searchable: true },
			{ id: "tags", label: "Tags", type: "tags", searchable: true },
			{ id: "updatedAt", label: "Saved at", type: "date" },
		],
	},
	{
		id: "reading-list",
		name: "Reading list",
		description: "Articles and long-form links with a lightweight reading status.",
		icon: "rss",
		defaultKind: "bookmark",
		fields: [
			{ id: "title", label: "Title", type: "text", searchable: true },
			{ id: "summary", label: "Excerpt", type: "text", searchable: true },
			{ id: "url", label: "URL", type: "url", searchable: true },
			{ id: "tags", label: "Topics", type: "tags", searchable: true },
			{ id: "updatedAt", label: "Saved at", type: "date" },
		],
	},
];

const githubSchema = schemaPresets[0]!;
const tangledSchema = schemaPresets[1]!;

export const defaultProviders: Provider[] = [
	{
		id: "github",
		name: "GitHub",
		kind: "github",
		handle: "@alex",
		description: "Starred repositories and topic metadata.",
		accent: "#8b7cff",
		schema: githubSchema,
		connected: true,
		connectedAt: "2026-08-21T08:10:00.000Z",
		lastSyncedAt: "2026-09-08T14:31:00.000Z",
	},
	{
		id: "tangled",
		name: "Tangled",
		kind: "tangled",
		handle: "did:plc:alex",
		description: "Stars and follows across the AT Protocol graph.",
		accent: "#54c7a8",
		schema: tangledSchema,
		connected: true,
		connectedAt: "2026-08-24T17:42:00.000Z",
		lastSyncedAt: "2026-09-08T14:29:00.000Z",
	},
];

const ago = (days: number, hours = 0) => {
	const date = new Date("2026-09-08T14:35:00.000Z");
	date.setDate(date.getDate() - days);
	date.setHours(date.getHours() - hours);
	return date.toISOString();
};

export const defaultEntries: Entry[] = [
	{
		id: "github-vercel-ai",
		providerId: "github",
		schemaId: githubSchema.id,
		kind: "repository",
		title: "vercel / ai",
		summary: "Build AI-powered products with React, Svelte, Vue, and Solid.",
		url: "https://github.com/vercel/ai",
		author: "Vercel",
		authorHandle: "vercel",
		tags: ["ai", "typescript", "react"],
		starredAt: ago(1, 3),
		updatedAt: ago(0, 7),
		syncedAt: ago(0, 1),
		isRead: false,
		isPinned: true,
		language: "TypeScript",
		languageColor: "#3178c6",
		stars: 15200,
		forks: 2400,
	},
	{
		id: "tangled-fission",
		providerId: "tangled",
		schemaId: tangledSchema.id,
		kind: "repository",
		title: "fission / fission",
		summary: "A small, sharp web of composable tools for the open social web.",
		url: "https://tangled.org/fission/fission",
		author: "Fission",
		authorHandle: "@fission.codes",
		tags: ["atproto", "decentralized", "tools"],
		starredAt: ago(2, 6),
		updatedAt: ago(1, 8),
		syncedAt: ago(0, 2),
		isRead: false,
		isPinned: false,
		language: "Rust",
		languageColor: "#dea584",
		stars: 418,
		forks: 34,
	},
	{
		id: "github-astro",
		providerId: "github",
		schemaId: githubSchema.id,
		kind: "repository",
		title: "withastro / astro",
		summary: "The web framework for content-driven websites.",
		url: "https://github.com/withastro/astro",
		author: "Astro",
		authorHandle: "withastro",
		tags: ["frontend", "web", "performance"],
		starredAt: ago(4, 2),
		updatedAt: ago(1, 3),
		syncedAt: ago(0, 1),
		isRead: true,
		isPinned: false,
		language: "TypeScript",
		languageColor: "#3178c6",
		stars: 49800,
		forks: 4300,
	},
	{
		id: "tangled-pds",
		providerId: "tangled",
		schemaId: tangledSchema.id,
		kind: "repository",
		title: "atmosphere / pds-kit",
		summary: "Practical building blocks for portable, self-hosted data services.",
		url: "https://tangled.org/atmosphere/pds-kit",
		author: "Atmosphere",
		authorHandle: "@atmo.dev",
		tags: ["atproto", "self-hosting", "cloudflare"],
		starredAt: ago(5, 4),
		updatedAt: ago(3, 2),
		syncedAt: ago(0, 2),
		isRead: true,
		isPinned: false,
		language: "TypeScript",
		languageColor: "#3178c6",
		stars: 97,
		forks: 11,
	},
	{
		id: "github-effect",
		providerId: "github",
		schemaId: githubSchema.id,
		kind: "repository",
		title: "Effect-TS / effect",
		summary: "A powerful TypeScript library designed to help people easily create programs that are complex, synchronous, and asynchronous.",
		url: "https://github.com/Effect-TS/effect",
		author: "Effect",
		authorHandle: "Effect-TS",
		tags: ["typescript", "functional", "architecture"],
		starredAt: ago(7, 1),
		updatedAt: ago(2, 5),
		syncedAt: ago(0, 1),
		isRead: false,
		isPinned: false,
		language: "TypeScript",
		languageColor: "#3178c6",
		stars: 11800,
		forks: 620,
	},
	{
		id: "github-turso",
		providerId: "github",
		schemaId: githubSchema.id,
		kind: "repository",
		title: "tursodatabase / libsql",
		summary: "SQLite-compatible database with extensions for the modern edge.",
		url: "https://github.com/tursodatabase/libsql",
		author: "Turso",
		authorHandle: "tursodatabase",
		tags: ["database", "edge", "rust"],
		starredAt: ago(10, 5),
		updatedAt: ago(4, 1),
		syncedAt: ago(0, 1),
		isRead: true,
		isPinned: false,
		language: "Rust",
		languageColor: "#dea584",
		stars: 10400,
		forks: 490,
	},
	{
		id: "tangled-solar",
		providerId: "tangled",
		schemaId: tangledSchema.id,
		kind: "repository",
		title: "solarpunk / garden",
		summary: "A calm, local-first reference implementation for personal knowledge graphs.",
		url: "https://tangled.org/solarpunk/garden",
		author: "Solarpunk",
		authorHandle: "@garden.social",
		tags: ["local-first", "knowledge", "design"],
		starredAt: ago(13, 2),
		updatedAt: ago(5, 8),
		syncedAt: ago(0, 2),
		isRead: true,
		isPinned: false,
		language: "Go",
		languageColor: "#00add8",
		stars: 146,
		forks: 9,
	},
	{
		id: "github-shadcn-ui",
		providerId: "github",
		schemaId: githubSchema.id,
		kind: "repository",
		title: "shadcn-ui / ui",
		summary: "Beautifully designed components that you can copy and paste into your apps.",
		url: "https://github.com/shadcn-ui/ui",
		author: "shadcn",
		authorHandle: "shadcn",
		tags: ["design-system", "react", "components"],
		starredAt: ago(18, 4),
		updatedAt: ago(6, 4),
		syncedAt: ago(0, 1),
		isRead: false,
		isPinned: false,
		language: "TypeScript",
		languageColor: "#3178c6",
		stars: 92000,
		forks: 6800,
	},
];

export const defaultCollections: Collection[] = [
	{
		id: "all",
		name: "All saves",
		description: "Everything from every connected source.",
		icon: "inbox",
		color: "#a9b6ad",
		rule: {},
		builtIn: true,
	},
	{
		id: "unread",
		name: "Unread",
		description: "Saved things you have not opened yet.",
		icon: "sparkles",
		color: "#f6c453",
		rule: { unreadOnly: true },
		builtIn: true,
	},
	{
		id: "pinned",
		name: "Pinned",
		description: "Your small set of things worth keeping close.",
		icon: "bookmark",
		color: "#f28a6b",
		rule: { pinnedOnly: true },
		builtIn: true,
	},
	{
		id: "github-stars",
		name: "GitHub stars",
		description: "Every repository starred on GitHub.",
		icon: "github",
		color: "#8b7cff",
		rule: { providerIds: ["github"] },
		builtIn: true,
	},
	{
		id: "tangled-stars",
		name: "Tangled stars",
		description: "Every repository starred on Tangled.",
		icon: "branch",
		color: "#54c7a8",
		rule: { providerIds: ["tangled"] },
		builtIn: true,
	},
	{
		id: "reading-queue",
		name: "Reading queue",
		description: "Ideas and links tagged read-later.",
		icon: "layers",
		color: "#d18df2",
		rule: { tags: ["read-later"] },
		builtIn: false,
	},
];

const backfillCandidates: Entry[] = [
	{
		id: "github-quiet-db",
		providerId: "github",
		schemaId: githubSchema.id,
		kind: "repository",
		title: "quiet-org / quiet-db",
		summary: "A tiny embedded database for calm, offline-friendly applications.",
		url: "https://github.com/quiet-org/quiet-db",
		author: "Quiet Org",
		authorHandle: "quiet-org",
		tags: ["local-first", "database", "typescript"],
		starredAt: "2026-09-08T13:54:00.000Z",
		updatedAt: "2026-09-08T13:54:00.000Z",
		syncedAt: "",
		isRead: false,
		isPinned: false,
		language: "TypeScript",
		languageColor: "#3178c6",
		stars: 82,
		forks: 4,
	},
	{
		id: "tangled-lumen",
		providerId: "tangled",
		schemaId: tangledSchema.id,
		kind: "repository",
		title: "lumen / little-signals",
		summary: "A small set of primitives for expressive, resilient interfaces.",
		url: "https://tangled.org/lumen/little-signals",
		author: "Lumen",
		authorHandle: "@lumen.place",
		tags: ["ui", "signals", "design"],
		starredAt: "2026-09-08T12:24:00.000Z",
		updatedAt: "2026-09-08T12:24:00.000Z",
		syncedAt: "",
		isRead: false,
		isPinned: false,
		language: "TypeScript",
		languageColor: "#3178c6",
		stars: 31,
		forks: 2,
	},
];

export function createBackfillEntries(providers: Provider[], existingIds: Set<string>): Entry[] {
	const connectedIds = new Set(providers.filter((provider) => provider.connected).map((provider) => provider.id));
	return backfillCandidates
		.filter((entry) => connectedIds.has(entry.providerId) && !existingIds.has(entry.id))
		.map((entry) => ({ ...entry, syncedAt: new Date().toISOString() }));
}
