export type EntryKind = "repository" | "bookmark" | "thread" | "video" | "note";

/** Built-ins are named here; string extension keeps provider additions schema/plugin driven. */
export type ProviderKind = "github" | "tangled" | "custom" | (string & {});

export type ProviderSchemaFieldType = "text" | "url" | "date" | "tags" | "number";

export type JsonPrimitive = string | number | boolean | null;
export type JsonValue = JsonPrimitive | JsonValue[] | { [key: string]: JsonValue };
export type EntryFields = Record<string, JsonValue>;

export interface ProviderSchemaField {
	id: string;
	label: string;
	type: ProviderSchemaFieldType;
	searchable?: boolean;
}

export interface ProviderSchema {
	id: string;
	name: string;
	description: string;
	icon: "github" | "branch" | "bookmark" | "rss";
	defaultKind: EntryKind;
	fields: ProviderSchemaField[];
}

export interface Provider {
	id: string;
	name: string;
	kind: ProviderKind;
	handle: string;
	description: string;
	accent: string;
	schema: ProviderSchema;
	connected: boolean;
	connectedAt?: string;
	lastSyncedAt?: string;
	syncPending?: boolean;
	settings?: Record<string, JsonValue>;
}

export interface Entry {
	id: string;
	providerId: string;
	schemaId: string;
	externalId?: string;
	kind: EntryKind;
	title: string;
	summary: string;
	url: string;
	author: string;
	authorHandle: string;
	tags: string[];
	starredAt: string;
	updatedAt: string;
	syncedAt: string;
	isRead: boolean;
	isPinned: boolean;
	language?: string;
	languageColor?: string;
	stars?: number;
	forks?: number;
	comments?: number;
	/** Provider-specific normalized fields, rendered according to ProviderSchema. */
	fields?: EntryFields;
	/** Optional vector generated by a configured semantic indexer. */
	embedding?: number[];
	/** Optional classifier output. Kept reviewable and separate from user tags. */
	classification?: {
		topics: string[];
		confidence?: number;
		model?: string;
	};
}

export interface CollectionRule {
	providerIds?: string[];
	tags?: string[];
	anyTags?: string[];
	kinds?: EntryKind[];
	unreadOnly?: boolean;
	pinnedOnly?: boolean;
}

export interface Collection {
	id: string;
	name: string;
	description: string;
	icon: "inbox" | "sparkles" | "bookmark" | "github" | "branch" | "layers";
	color: string;
	rule: CollectionRule;
	builtIn: boolean;
}

export type AutomationTrigger = "entry.created" | "entry.updated" | "sync.completed" | "manual";
export type AutomationAction = "tag" | "classify" | "webhook";

export interface Automation {
	id: string;
	name: string;
	description: string;
	trigger: AutomationTrigger;
	action: AutomationAction;
	config: Record<string, JsonValue>;
	enabled: boolean;
	createdAt: string;
	updatedAt: string;
}

export interface PluginManifest {
	id: string;
	name: string;
	version: string;
	description: string;
	permissions: string[];
	triggers: AutomationTrigger[];
	actions: AutomationAction[];
	entrypoint?: string;
	enabled: boolean;
}

export type SearchMode = "hybrid" | "fuzzy" | "semantic";
