import type { Collection, ProviderSchema } from "./types";

export const schemaPresets: ProviderSchema[] = [
	{
		id: "github-repository",
		name: "Starred repositories",
		description: "Repositories, topics, languages, and the date you starred them.",
		icon: "github",
		defaultKind: "repository",
		fields: [
			{ id: "title", label: "Repository", type: "text", searchable: true },
			{ id: "summary", label: "Description", type: "text", searchable: true },
			{ id: "language", label: "Language", type: "text", searchable: true },
			{ id: "tags", label: "Topics", type: "tags", searchable: true },
			{ id: "stars", label: "Stars", type: "number" },
			{ id: "starredAt", label: "Starred at", type: "date" },
		],
	},
	{
		id: "tangled-repository",
		name: "Tangled stars",
		description: "AT Protocol repositories and conversations from Tangled.",
		icon: "branch",
		defaultKind: "repository",
		fields: [
			{ id: "title", label: "Repository", type: "text", searchable: true },
			{ id: "summary", label: "Description", type: "text", searchable: true },
			{ id: "authorHandle", label: "Author", type: "text", searchable: true },
			{ id: "tags", label: "Topics", type: "tags", searchable: true },
			{ id: "starredAt", label: "Starred at", type: "date" },
		],
	},
	{
		id: "web-bookmark",
		name: "Web bookmarks",
		description: "A general-purpose URL schema for any future bookmark provider.",
		icon: "bookmark",
		defaultKind: "bookmark",
		fields: [
			{ id: "title", label: "Title", type: "text", searchable: true },
			{ id: "summary", label: "Notes", type: "text", searchable: true },
			{ id: "url", label: "URL", type: "url", searchable: true },
			{ id: "tags", label: "Tags", type: "tags", searchable: true },
			{ id: "updatedAt", label: "Saved at", type: "date" },
		],
	},
	{
		id: "reading-list",
		name: "Reading list",
		description: "Articles and long-form links with a lightweight reading status.",
		icon: "rss",
		defaultKind: "bookmark",
		fields: [
			{ id: "title", label: "Title", type: "text", searchable: true },
			{ id: "summary", label: "Excerpt", type: "text", searchable: true },
			{ id: "url", label: "URL", type: "url", searchable: true },
			{ id: "tags", label: "Topics", type: "tags", searchable: true },
			{ id: "updatedAt", label: "Saved at", type: "date" },
		],
	},
];

export const defaultCollections: Collection[] = [
	{
		id: "all",
		name: "All saves",
		description: "Everything from every connected source.",
		icon: "inbox",
		color: "#a9b6ad",
		rule: {},
		builtIn: true,
	},
	{
		id: "unread",
		name: "Unread",
		description: "Saved things you have not opened yet.",
		icon: "sparkles",
		color: "#f6c453",
		rule: { unreadOnly: true },
		builtIn: true,
	},
	{
		id: "pinned",
		name: "Pinned",
		description: "Your small set of things worth keeping close.",
		icon: "bookmark",
		color: "#f28a6b",
		rule: { pinnedOnly: true },
		builtIn: true,
	},
	{
		id: "github-stars",
		name: "GitHub stars",
		description: "Every repository starred on GitHub.",
		icon: "github",
		color: "#8b7cff",
		rule: { providerIds: ["github"] },
		builtIn: true,
	},
	{
		id: "tangled-stars",
		name: "Tangled stars",
		description: "Every repository starred on Tangled.",
		icon: "branch",
		color: "#54c7a8",
		rule: { providerIds: ["tangled"] },
		builtIn: true,
	},
	{
		id: "reading-queue",
		name: "Reading queue",
		description: "Ideas and links tagged read-later.",
		icon: "layers",
		color: "#d18df2",
		rule: { tags: ["read-later"] },
		builtIn: false,
	},
];
